version: "3.8"

volumes:
  mysql:
    name: mysql
    external: true
  prometheus:
    name: prometheus
    external: true
  grafana:
    name: grafana
    external: true
  wordpress:
    name: wordpress
    external: true
  matomo:
    name: matomo
    external: true
  resourcespace:
    name: resourcespace
    external: true
  nextcloud:
    name: nextcloud
    external: true
  portainer:
    name: portainer
    external: true
  unifi-controller:
    name: unifi-controller
    external: true
  kolibri:
    name: kolibri
    external: true
  jellyfin:
    name: jellyfin
    external: true

services:
  backup:
    container_name: backup
    image: ubuntu
    volumes:
      - wordpress:/volumes/wordpress
      - grafana:/volumes/grafana
      - prometheus:/volumes/prometheus
      - mysql:/volumes/mysql
      - matomo:/volumes/matomo
      - resourcespace:/volumes/resourcespace
      - nextcloud:/volumes/nextcloud
      - portainer:/volumes/portainer
      - unifi-controller:/volumes/unifi-controller
      - kolibri:/volumes/kolibri
      - jellyfin:/volumes/jellyfin
      - ${THIS_BACKUP_DIR}:${THIS_BACKUP_DIR}
    command: ["/bin/sh", "-c", "tar cf - /volumes | gzip -9 > ${THIS_BACKUP_DIR}/${TIMESTAMP}.volumes.tar.gzip"]
