services:
  odoo:
    # user: "{{uid}}:{{gid}}"
    image: odoo:{{app_version}}
    command: ["--proxy-mode"{% if app_first_install %},"-i", "base"{% endif %}]
    restart: unless-stopped
    networks:
      - traefik
      - postgres
    environment:
    - HOST=postgres
    - POSTGRES_USER={{app_db_user}}
    - POSTGRES_PASSWORD={{app_db_password}}
    volumes:
    - {{app_root}}/data:/var/lib/odoo
    - {{app_root}}/addons:/mnt/extra-addons
    - {{app_root}}/config:/etc/odoo
{% include "labels.yml" %}

networks:
  traefik:
    external: true
  postgres:
    external: true