version: "3.8"

networks:
  mail:
    name: mail

services:
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    networks:
      - traefik
      - mail
    labels:
      traefik.enable: "true"
      traefik.http.routers.mailhog.entrypoints: websecure
      traefik.http.routers.mailhog.rule: Host(`${DOMAIN_MAILHOG}`)
      traefik.http.routers.mailhog.tls: "true"
      traefik.http.services.mailhog.loadbalancer.server.port: 8025
      traefik.http.routers.mailhog.middlewares: traefik-auth
    restart: unless-stopped

  matomo:
    networks:
      - mail
    depends_on:
      - mailhog

  netdata:
    labels:
      traefik.http.routers.netdata.middlewares: traefik-auth

  prometheus:
    labels:
      traefik.http.routers.prometheus.middlewares: traefik-auth

  resourcespace:
    networks:
      - mail
    depends_on:
      - mailhog

  traefik:
    command:
      - --accessLog=true
      - --api.insecure=false
      - --api.dashboard=true
      - --api.debug=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entryPoints.metrics.address=:8082
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --log.level=WARNING
      - --metrics.prometheus=true
      - --metrics.prometheus.buckets=0.100000, 0.300000, 1.200000, 5.000000
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addServicesLabels=true
      - --metrics.prometheus.entryPoint=metrics
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik
      - --providers.file.directory=/config
      - --providers.file.watch=true
    volumes:
      - ./config/services/traefik/config/local:/config
      - ${ACME_CERTS_DIR}/${ACME_DOMAIN}.cer:/certs/lokal.cer
      - ${ACME_CERTS_DIR}/${ACME_DOMAIN}.key:/certs/lokal.key
    labels:
      traefik.http.middlewares.traefik-auth.basicauth.users: ${TRAEFIK_BASICAUTH_USERS}
      traefik.http.routers.traefik.middlewares: traefik-auth

  transmission:
    labels:
      traefik.http.routers.transmission.middlewares: traefik-auth

  wordpress:
    networks:
      - mail
    depends_on:
      - mailhog
