version: "3.8"

networks:
  mail:
    name: mail

services:
  fileserver:
    container_name: fileserver
    image: caddy
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.fileserver.entrypoints: websecure
      traefik.http.routers.fileserver.rule: Host(`get.${DOMAIN}`, `${PUBLIC_GET_DOMAIN}`)
      traefik.http.routers.fileserver.tls: "true"
      traefik.http.routers.fileserver.tls.certresolver: dns
      traefik.http.services.fileserver.loadbalancer.server.port: 80
    networks:
      - traefik
    volumes:
      - ./config/services/get/:/usr/share/caddy/
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    networks:
      - traefik
      - mail
    labels:
      traefik.enable: "true"
      traefik.http.routers.mailhog.entrypoints: websecure
      traefik.http.routers.mailhog.rule: Host(`${DOMAIN_MAILHOG}`)
      traefik.http.routers.mailhog.tls: "true"
      traefik.http.services.mailhog.loadbalancer.server.port: 8025
      traefik.http.routers.mailhog.tls.certresolver: ${CERT_RESOLVER}
      traefik.http.routers.mailhog.middlewares: traefik-auth
    restart: unless-stopped

  matomo:
    networks:
      - mail
    depends_on:
      - mailhog

  resourcespace:
    networks:
      - mail
    depends_on:
      - mailhog

  wordpress:
    networks:
      - mail
    depends_on:
      - mailhog
