---
- name: Create {{app}} minio bucket
  ansible.builtin.shell:
    cmd: >
      docker compose exec minio
      mc mb --ignore-existing local/{{minio_bucket}}
    chdir: "{{project_root}}/lokal"

- name: Create {{app}} minio bucket
  ansible.builtin.shell:
    cmd: >
      docker compose exec minio
      mc admin user add local {{minio_user}} {{minio_password}}
    chdir: "{{project_root}}/lokal"

- name: Render minio policy
  ansible.builtin.template:
    src: policy.json
    dest: "{{project_root}}/lokal/minio/config/policies/{{app}}.json"

- name: List current policies
  ansible.builtin.shell:
    cmd: >
      docker compose exec minio
      mc admin policy ls local
    chdir: "{{project_root}}/lokal"
  register: minio_policies

- name: Create {{app}} minio policy
  ansible.builtin.shell:
    cmd: >
      docker compose exec minio
      mc admin policy create local {{app}} /.mc/policies/{{app}}.json
    chdir: "{{project_root}}/lokal"
  when: "app not in minio_policies.stdout"

- name: Apply {{app}} minio policy
  ansible.builtin.shell:
    cmd: >
      docker compose exec minio
      mc admin policy attach local {{app}} --user {{minio_user}}
    chdir: "{{project_root}}/lokal"
  when: "app not in minio_policies.stdout"

