---
- name: Create {{app}} minio bucket
  ansible.builtin.shell:
    cmd: >
      docker compose exec minio
      mc mb --ignore-existing local/{{minio_bucket}}
    chdir: "{{project_root}}/lokal"

- name: Create {{app}} minio bucket
  ansible.builtin.shell:
    cmd: >
      docker compose exec minio
      mc admin user add local {{minio_user}} {{minio_password}}
    chdir: "{{project_root}}/lokal"

- name: Render minio policy
  ansible.builtin.template:
    src: policy.json
    dest: /tmp/{{app}}-policy.json

- name: Create {{app}} minio bucket
  ansible.builtin.shell:
    cmd: >
      docker compose exec minio
      mc admin policy attach local {{app}} --user {{minio_user}} /tmp/{{app}}-policy.json
    chdir: "{{project_root}}/lokal"

