---
- name: Install azuracast
  ansible.builtin.include_role:
    name: common
    tasks_from: install
  vars:
    app: azuracast
    app_version: "{{version_azuracast}}"
    # local mysql is included in the container and there is no way using our own
    data_dirs:
    - uploads
    - stations
    - shoutcast2
    - stereo_tool
    - geolite
    - sftp
    - backups
    - acme
    - db
    start: false
    firewall_tcp:
    # Azuracast SFTP
    - 2022
    # Azuracast Stations
    - 8000
    - 8005
    - 8006
    - 8010
    - 8015
    - 8016
    - 8020
    - 8025
    - 8026
    - 8030
    - 8035
    - 8036
    - 8040
    - 8045
    - 8046
    - 8050
    - 8055
    - 8056
    - 8060
    - 8065
    - 8066
    - 8070
    - 8075
    - 8076
    - 8090
    - 8095
    - 8096
    - 8100
    - 8105
    - 8106
    - 8110
    - 8115
    - 8116
    - 8120
    - 8125
    - 8126
    - 8130
    - 8135
    - 8136
    - 8140
    - 8145
    - 8146
    - 8150
    - 8155
    - 8156
    - 8160
    - 8165
    - 8166
    - 8170
    - 8175
    - 8176
    - 8180
    - 8185
    - 8186
    - 8190
    - 8195
    - 8196
    - 8200
    - 8205
    - 8206
    - 8210
    - 8215
    - 8216
    - 8220
    - 8225
    - 8226
    - 8230
    - 8235
    - 8236
    - 8240
    - 8245
    - 8246
    - 8250
    - 8255
    - 8256
    - 8260
    - 8265
    - 8266
    - 8270
    - 8275
    - 8276
    - 8280
    - 8285
    - 8286
    - 8290
    - 8295
    - 8296
    - 8300
    - 8305
    - 8306
    - 8310
    - 8315
    - 8316
    - 8320
    - 8325
    - 8326
    - 8330
    - 8335
    - 8336
    - 8340
    - 8345
    - 8346
    - 8350
    - 8355
    - 8356
    - 8360
    - 8365
    - 8366
    - 8370
    - 8375
    - 8376
    - 8380
    - 8385
    - 8386
    - 8390
    - 8395
    - 8396
    - 8400
    - 8405
    - 8406
    - 8410
    - 8415
    - 8416
    - 8420
    - 8425
    - 8426
    - 8430
    - 8435
    - 8436
    - 8440
    - 8445
    - 8446
    - 8450
    - 8455
    - 8456
    - 8460
    - 8465
    - 8466
    - 8470
    - 8475
    - 8476
    - 8480
    - 8485
    - 8486
    - 8490
    - 8495
    - 8496

- name: Prepare installation
  ansible.builtin.shell:
    cmd: docker-compose run --rm azuracast -- azuracast_install && touch installed
    chdir: "{{app_root}}"
    creates: "installed"
  when: not app_upgrade is defined or not app_upgrade

- name: Update app
  ansible.builtin.shell:
    cmd: docker-compose run --rm azuracast -- azuracast_update
    chdir: "{{app_root}}"
  when: app_upgrade is defined and app_upgrade is truthy

- name: Docker-compose up
  ansible.builtin.shell:
    cmd: docker-compose up -d
    chdir: "{{app_root}}"