---
- name: Install grafana
  ansible.builtin.include_role:
    name: lokal
    tasks_from: install
  vars:
    app: grafana
    data_dirs:
    - data
    mysql_db: "{{mysql_database_grafana}}"
    mysql_user: "{{mysql_user_grafana}}"
    mysql_password: "{{mysql_pass_grafana}}"