---
- name: Deploy Services
  hosts: all
  tasks:
    - name: Docker-compose pull
      shell: "direnv exec . dc pull traefik grafana netdata prometheus portainer wordpress matomo transmission unifi-poller unifi-controller jellyfin"
      args:
        chdir: "{{ git_dest }}"

    - name: Docker-compose up mariadb
      shell: "direnv exec . dc up -d mariadb"
      args:
        chdir: "{{ git_dest }}"

    - name: Docker-compose up
      shell: "direnv exec . dc up -d"
      args:
        chdir: "{{ git_dest }}"
