---
- name: Deploy Services
  hosts: all
  tasks:

    - name: Register primary user's details
      user:
        name: "{{ primary_ssh_user }}"
      register: primary_ssh_user_params

    - name: Set facts
      set_fact:
        jitsi_project: "docker-jitsi-meet"
        jitsi_release: "stable-5870"
        domain_jitsi: "meet.vnet.lan"

    - name: Set more facts
      set_fact:
        jitsi_dest: "{{ primary_ssh_user_params.home }}/{{ jitsi_project }}-{{ jitsi_release }}"
        git_dest: "{{ primary_ssh_user_params.home }}/{{ repo_name }}"

    - name: Set passwords
      set_fact:
        jicofo_auth_password: "{{ lookup('password', '{{ jitsi_dest }}/.ansible.pass/jicofo_auth_password length=16 chars=ascii_letters') }}"
        jvb_auth_password: "{{ lookup('password', '{{ jitsi_dest }}/.ansible.pass/jvb_auth_password length=16 chars=ascii_letters') }}"
        jigasi_xmpp_password: "{{ lookup('password', '{{ jitsi_dest }}/.ansible.pass/jigasi_xmpp_password length=16 chars=ascii_letters') }}"
        jibri_recorder_password: "{{ lookup('password', '{{ jitsi_dest }}/.ansible.pass/jibri_recorder_password length=16 chars=ascii_letters') }}"
        jibri_xmpp_password: "{{ lookup('password', '{{ jitsi_dest }}/.ansible.pass/jibri_xmpp_password length=16 chars=ascii_letters') }}"

    - name: Unarchive latest jitsi source
      ansible.builtin.unarchive:
        src: https://github.com/jitsi/{{ jitsi_project }}/archive/refs/tags/{{ jitsi_release }}.zip
        dest: "{{ primary_ssh_user_params.home }}"
        remote_src: yes

    - name: Make a backup of original docker-compose file
      ansible.builtin.copy:
        src: "{{ jitsi_dest }}/docker-compose.yml"
        dest: "{{ jitsi_dest }}/docker-compose.yml.bak"

    - name: Copy .env from template
      ansible.builtin.template:
        src: "{{ git_dest }}/config/services/jitsi/.env.j2"
        dest: "{{ jitsi_dest }}/.env"

    - name: Copy docker-compose.yml from template
      ansible.builtin.template:
        src: "{{ git_dest }}/config/services/jitsi/docker-compose.yml.j2"
        dest: "{{ jitsi_dest }}/docker-compose.yml"

    - name: Get .env file content
      shell: . {{ jitsi_dest }}/.env && env
      register: env_file_result

    - name: Parse environment
      set_fact:
        env_vars: "{{ ('{' + env_file_result.stdout_lines | map('regex_replace', '([^=]*)=(.*)', '\"\\1\": \"\\2\"') | join(',') + '}') | from_json }}"

    - name: Display environment variables
      command: env
      debugger: always
      environment: "{{ env_vars }}"

    - name: Create directories
      file:
        path: "{{ lookup('env', 'CONFIG') }}/{{ item }}"
        state: directory
      environment: "{{ env_vars }}"
      with_items:
        - web/letsencrypt
        - transcripts
        - prosody/config
        - prosody/prosody-plugins-custom
        - jicofo
        - jvb
        - jigasi
        - jibri
