---
- name: Deploy Moodle
  hosts: all
  tasks:

    - name: Register primary user's details
      user:
        name: "{{ primary_ssh_user }}"
      register: primary_ssh_user_params

    - name: Set facts
      set_fact:
        lokal_dir: "{{ primary_ssh_user_params.home }}/Lokal"
        moodle_dir: "{{ primary_ssh_user_params.home }}/moodle"

    - name: Make Moodle installation directory
      file:
        path: "{{ moodle_dir }}"
        state: directory

    - name: Get .envrc file content
      shell: . {{ lokal_dir }}/.envrc && env
      register: envrc_out

    - name: Parse environment
      set_fact:
        envrc: "{{ ('{' + envrc_out.stdout_lines | map('regex_replace', '([^=]*)=(.*)', '\"\\1\": \"\\2\"') | join(',') + '}') | from_json }}"

    - name: Set facts
      set_fact:
        domain_moodle: "moodle.{{ envrc.DOMAIN }}"
        cert_resolver: "{{ envrc.CERT_RESOLVER | default('dns') }}"
        server_is_live: "{{ envrc.SERVER_IS_LIVE | default(false) }}"

    - name: Copy .env from template
      ansible.builtin.template:
        src: "{{ lokal_dir }}/config/services/moodle/.env.j2"
        dest: "{{ moodle_dir }}/.env"
        mode: "0600"

    - name: Copy docker-compose.yml from template
      ansible.builtin.template:
        src: "{{ lokal_dir }}/config/services/moodle/docker-compose.yml.j2"
        dest: "{{ moodle_dir }}/docker-compose.yml"
        mode: "0600"

    - name: "Setup Moodle for stable releases"
      shell: "docker-compose up -d"
      args:
        chdir: "{{ moodle_dir }}"
