ungrouped:
  hosts:
    dnwt-nuc-03:
      ansible_user: ubuntu
      ansible_ssh_host: 10.179.0.10
      ansible_connection: ssh
    dnwt-nuc-04:
      ansible_user: ubuntu
      ansible_ssh_host: 10.179.0.13
      ansible_connection: ssh
