---
- name: Extra tasks for when provisioning a machine image
  hosts: all
  become: yes
  tasks:
    - name: Register cloud provided ssh user's details
      user:
        name: "{{ root_ssh_user }}"
      register: root_ssh_user_params

    - name: Register primary user's details
      user:
        name: "{{ primary_ssh_user }}"
      register: primary_ssh_user_params

    - name: Ensure authorized keys are reset for all users
      copy:
        content: ""
        dest: "{{ item.home }}/.ssh/authorized_keys"
        group: "{{ item.user }}"
        owner: "{{ item.user }}"
        mode: 0600
      with_items:
        - user: "{{ root_ssh_user }}"
          home: "{{ root_ssh_user_params.home }}"
        - user: "{{ primary_ssh_user }}"
          home: "{{ primary_ssh_user_params.home }}"
      become: yes
