---
- name: Install lokal
  hosts: all
  roles:
  - common

  handlers:
  - name: Restart router
    ansible.builtin.shell:
      cmd: docker compose restart traefik
      chdir: "{{project_root}}/base"
    ignore_errors: yes

  - name: Reload docker
    become: true
    ansible.builtin.shell:
      cmd: "kill -s SIGHUP `pidof dockerd`"

  tasks:
  - name: Install all services
    loop: "{{services}}"
    loop_control:
      loop_var: service
    include_role:
      name: "{{service}}"
      tasks_from: "main"
    when: '(not install is defined and not remove is defined and not backup is defined and not restore is defined) or (install is defined and install == "all")'

  - name: Check selected service is listed in services variable
    ansible.builtin.fail:
      msg: "Services to install: {{install}} are not defined in services variable: {{services}}"
    when: "install is defined and install|split(',')|difference(services) is truthy"

  - name: Install specified services
    loop: "{{ install | split(',') }}"
    loop_control:
      loop_var: service
    include_role:
      name: "{{service}}"
      tasks_from: "main"
    when: "install is defined and install|split(',')|difference(services) is falsy"

  - name: Check selected services for backup were installed
    ansible.builtin.fail:
      msg: "Services to backup: {{backup}} are not defined in services variable: {{services}}"
    when: "backup is defined and backup != 'all' and backup|split(',')|difference(services) is truthy"

  - name: Backup specified services
    loop: "{{ backup | split(',') }}"
    loop_control:
      loop_var: service
    include_role:
      name: "{{service}}"
      tasks_from: "backup"
    when: "backup is defined and backup != 'all' and backup|split(',')|difference(services) is falsy"

  - name: Backup all services
    when: backup is defined and backup == 'all'
    loop: "{{services}}"
    loop_control:
      loop_var: service
    include_role:
      name: "{{service}}"
      tasks_from: "backup"

  - name: Check selected services for restore were at least installed
    ansible.builtin.fail:
      msg: "Services to restore: {{restore}} are not defined in services variable: {{services}}"
    when: "restore is defined and restore != 'all' and restore|split(',')|difference(services) is truthy"

  - name: Restore specified services
    loop: "{{ restore | split(',') }}"
    loop_control:
      loop_var: service
    include_role:
      name: "{{service}}"
      tasks_from: "restore"
    when: "restore is defined and restore != 'all' and restore|split(',')|difference(services) is falsy"

  - name: Restore all services
    loop: "{{services}}"
    loop_control:
      loop_var: service
    include_role:
      name: "{{service}}"
      tasks_from: "restore"
    when: "restore is defined and restore == 'all'"

  - name: Remove services
    loop: "{{ remove | split(',') }}"
    loop_control:
      loop_var: service
    include_role:
      name: "{{service}}"
      tasks_from: "remove"
    when: "remove is defined and remove|split(',')|difference(services) is falsy"
