---
- name: Install lokal
  hosts: all
  roles:
  - common

  tasks:
  - name: Install services
    loop: "{{services}}"
    loop_control:
      loop_var: service
    include_role:
      name: "{{service}}"
      tasks_from: "main"
    when: "not backup is defined and not restore is defined and not install is defined"

  - name: Install services
    loop: "{{ install | split(',') }}"
    loop_control:
      loop_var: service
    include_role:
      name: "{{service}}"
      tasks_from: "main"
    when: "not backup is defined and not restore is defined and install is defined" #  and install|split(',')|difference(services) is falsy

  - name: Backup specified services
    when: "backup is defined and backup != 'all'"
    loop: "{{ backup | split(',') }}"
    loop_control:
      loop_var: service
    include_role:
      name: "{{service}}"
      tasks_from: "backup"

  - name: Backup all services
    when: "backup is defined and backup == 'all'"
    loop: "{{services}}"
    loop_control:
      loop_var: service
    include_role:
      name: "{{service}}"
      tasks_from: "backup"

  - name: Restore specified services
    when: "restore is defined and restore != 'all'"
    loop: "{{ restore | split(',') }}"
    loop_control:
      loop_var: service
    include_role:
      name: "{{service}}"
      tasks_from: "restore"

  - name: Restore all services
    when: "restore is defined and restore == 'all'"
    loop: "{{services}}"
    loop_control:
      loop_var: service
    include_role:
      name: "{{service}}"
      tasks_from: "restore"
