---
# - name: "Copy files for traefik"
#   ansible.builtin.copy:
#     src: files/traefik/config
#     dest: '{{project_root}}/base/traefik/'

- name: "Create directories"
  ansible.builtin.file:
    path: "{{ project_root }}/base/traefik/{{item}}"
    state: directory
    mode: 0700
  loop:
  - certs
  - acme
  - conf

- name: "Use static certs"
  ansible.builtin.template:
    src: dynamic.yml.j2
    dest: '{{project_root}}/base/traefik/conf/dynamic.yml'
  when: static_certificate is truthy

- name: "Use self signed certs"
  include_tasks:
    file: setup-traefik-with-self-signed-certs.yml
  when: not server_is_live and static_certificate is falsy
