---
- name: Install your-app
  include_role:
    name: lokal
    tasks_from: install
  vars:
    app: your-app
    app_dirs:
    - data
    - config
    app_templates:
      service.conf: config/service.conf
    app_db: "mysql"
    app_start: false # you can postpone starting (by defaults the container starts)

- name: Example copy of a file in your files/ folder
  ansible.builtin.copy:
    src: "files/your-static-file.txt"
    dest: "{{app_root}}/data/some-file.txt" # {{app_root}} is accessible because the lokal.install already ran
    force: false

# You can do more steps before finally launching your application

# This is the command to start your app manually
- name: Start the app
  ansible.builtin.shell:
    cmd: "docker compose up -d"
    chdir: "{{app_root}}"