---
- name: Export app_root variable
  ansible.builtin.set_fact:
    app_root: "{{project_root}}/{{app_domain}}"

- name: Get current version (could have been upgraded via web)
  ansible.builtin.shell:
    cmd: grep 'wp_version\s*=' wp-includes/version.php
    chdir: "{{app_root}}/app"
  ignore_errors: true
  register: version_output

- name: Parse out the version
  ansible.builtin.set_fact:
    version_runtime_wordpress: "{{version_output.stdout|regex_search('([\\d\\.]+)')}}"
  when: version_output is defined and version_output.stdout is defined

- name: Upgrade app (if wordpress_version is newer than already running version)
  ansible.builtin.include_tasks:
    file: upgrade.yml
  when: version_runtime_wordpress is defined and version_runtime_wordpress is truthy and version_runtime_wordpress is version(wordpress_version, '<')

- name: Install wordpress
  include_role:
    name: lokal
    tasks_from: install
  vars:
    app_domain: "{{wordpress_domain}}"
    app_db: "mysql"
    data_dirs:
    - app
    - data
    app_templates:
      php.ini: "php.ini"

- name: Wordpress initial installation
  ansible.builtin.shell:
    cmd: >
      docker compose run --rm wordpress_cli
      wp core install
        --url={{app_domain}}
        --title="{{wordpress_title}}"
        --admin_username={{admin_username}}
        --admin_password="{{admin_password}}"
        --admin_email={{admin_email}}
    chdir: "{{app_root}}"
  when: version_output is not defined

- name: Wordpress DB upgrade
  ansible.builtin.shell:
    cmd: docker compose run --rm wordpress_cli wp core update-db
    chdir: "{{app_root}}"
  when: version_runtime_wordpress is defined and version_runtime_wordpress is truthy and version_runtime_wordpress is version(wordpress_version, '<')
