---
- name: Get current version (could have been upgraded via web)
  ansible.builtin.shell:
    cmd: grep 'wp_version\s*=' wp-includes/version.php
    chdir: "{{project_root}}/wordpress/app"
  ignore_errors: true
  register: version_output

- name: Parse out the version
  ansible.builtin.set_fact:
    version_runtime_wordpress: "{{version_output.stdout|regex_search('([\\d\\.]+)')}}"
  when: version_output is defined and version_output.stdout is defined

- name: Upgrade app (if version_wordpress is newer than already running version)
  ansible.builtin.include_tasks:
    file: upgrade.yml
  when: version_runtime_wordpress is defined and version_runtime_wordpress is truthy and version_runtime_wordpress is version(version_wordpress, '<')

- name: Install wordpress
  include_role: {name: common, tasks_from: install}
  vars:
    app: wordpress
    mysql_user: "{{mysql_user_wordpress}}"
    mysql_password: "{{mysql_password_wordpress}}"
    mysql_db: "{{mysql_database_wordpress}}"
    data_dirs:
    - app
    - data