---
- name: Create app directory
  file:
    path: "{{ project_root }}/wordpress/data"
    state: directory

- name: Stop current app if it is already running
  ansible.builtin.shell:
    cmd: "docker-compose down"
    chdir: "{{ project_root }}/wordpress"
    removes: docker-compose.yml  # runs only when this file exists
  ignore_errors: yes # in case of corrupted docker-compose.yml this would interrupt the whole playbook

- name: Init database
  community.mysql.mysql_db:
    name: "{{mysql_database_wordpress}}"
    state: present
    login_user: root
    login_password: "{{mysql_root_password}}"
    login_host: localhost
    login_port: "{{mysql_port}}"

- name: Grant user priviledges to the DB
  community.mysql.mysql_user:
    name: "{{mysql_user_wordpress}}"
    password: "{{mysql_password_wordpress}}"
    priv: '{{mysql_database_wordpress}}.*:ALL'
    host: "%"
    state: present
    login_user: root
    login_password: "{{mysql_root_password}}"
    login_host: localhost
    login_port: "{{mysql_port}}"

- name: Render docker-compose.yml
  ansible.builtin.template:
    src: "compose.yml.j2"
    dest: "{{ project_root }}/wordpress/docker-compose.yml"
    mode: "0600"

- name: Docker-compose up
  ansible.builtin.shell: 
    cmd: "docker-compose up -d"
    chdir: "{{ project_root }}/wordpress/"
