---
- name: Create app directory
  file:
    path: "{{ project_root }}/wordpress/data"
    state: directory

- name: Init database
  community.mysql.mysql_db:
    name: "{{mysql_database_wordpress}}"
    state: present
    login_user: root
    login_password: "{{mysql_root_password}}"
    login_host: localhost

- name: Grant user priviledges to the DB
  community.mysql.mysql_user:
    name: "{{mysql_user_wordpress}}"
    password: "{{mysql_password_wordpress}}"
    priv: '{{mysql_database_wordpress}}.*:ALL'
    state: present
    login_user: root
    login_password: "{{mysql_root_password}}"
    login_host: localhost

- name: Render docker-compose.yml
  ansible.builtin.template:
    src: "compose.yml.j2"
    dest: "{{ project_root }}/wordpress/docker-compose.yml"
    mode: "0600"

- name: Docker-compose up
  shell: "docker-compose up -d"
  args:
    chdir: "{{ project_root }}/wordpress/"
