---
- name: Remove old container
  ansible.builtin.shell: 
    cmd: "docker-compose down"
    chdir: "{{ project_root }}/wordpress/"

- name: Clear app folder
  ansible.builtin.file:
    path: "{{ project_root }}/wordpress/app"
    state: absent

- name: Re-create the app folder
  ansible.builtin.file:
    path: "{{ project_root }}/wordpress/app"
    state: directory

- name: Render upgraded docker-compose.yml
  ansible.builtin.template:
    src: "compose.yml.j2"
    dest: "{{ project_root }}/wordpress/docker-compose.yml"
    mode: "0600"

- name: Docker-compose up
  ansible.builtin.shell: 
    cmd: "docker-compose up -d"
    chdir: "{{ project_root }}/wordpress/"

- name: Database upgrade
  ansible.builtin.debug:
    msg: Please visit https://{{domain}}/wp-admin/upgrade.php to run the DB upgrade
