---
- name: Remove old container
  ansible.builtin.shell: 
    cmd: "docker compose down"
    chdir: "{{ project_root }}/wordpress/"

- name: Clear app folder
  ansible.builtin.file:
    path: "{{ project_root }}/wordpress/app"
    state: absent

- name: Re-create the app folder
  ansible.builtin.file:
    path: "{{ project_root }}/wordpress/app"
    state: directory
