---
- name: Remove old container
  ansible.builtin.shell:
    cmd: "docker compose down"
    chdir: "{{app_root}}"

- name: Clear app folder
  ansible.builtin.file:
    path: "{{app_root}}/app"
    state: absent

- name: Re-create the app folder
  ansible.builtin.file:
    path: "{{app_root}}/app"
    state: directory
