---
- name: Install matrix
  include_role:
    name: lokal
    tasks_from: install
  vars:
    app: matrix
    data_dirs:
    - data
    - config
    - element
    postgres_db: "{{postgres_db_matrix}}"
    postgres_user: "{{postgres_user_matrix}}"
    postgres_password: "{{postgres_password_matrix}}"
    firewall_tcp:
    - "3478"
    - "5349"
    - "49152:65535"
    firewall_udp:
    - "3478"
    - "5349"
    - "49152:65535"
    start: false

- name: Render element config
  ansible.builtin.template:
    src: "element.json.j2"
    dest: "{{app_root}}/element/config.json"
    force: false

- name: Generate config and keys
  ansible.builtin.shell:
    cmd: >
      docker run -it --rm
      --user {{uid}}:{{gid}}
      --mount type=bind,src={{app_root}}/data,dst=/data
      -e SYNAPSE_SERVER_NAME={{subdomain_matrix}}.{{domain}}
      -e SYNAPSE_REPORT_STATS=no
      matrixdotorg/synapse:latest generate
    creates: "{{app_root}}/data/homeserver.yaml"

- name: Decide user creation (setup by enable_registration_matrix)
  ansible.builtin.lineinfile:
    line: "{{item}}: {{enable_registration_matrix|to_json}}"
    regex: "{{item}}.*"
    path: "{{app_root}}/data/homeserver.yaml"
    state: present
  notify: "matrix : restart"
  loop:
  - enable_registration
  - enable_registration_without_verification

- name: Start matrix app
  ansible.builtin.shell:
    cmd: docker compose up -d
    chdir: "{{app_root}}"

- name: Wait for the server to start up
  ansible.builtin.pause:
    seconds: 5

- name: Ensure Synapse admin user registered exists
  ansible.builtin.command:
    chdir: "{{app_root}}"
    cmd: >
      docker compose exec matrix
      register_new_matrix_user
      -u admin
      -p "{{ admin_password_matrix }}"
      -c /data/homeserver.yaml --admin
      http://localhost:8008
  register: matrix_synapse_register_user_result
  changed_when: matrix_synapse_register_user_result.rc == 0 and 'User ID already taken' not in matrix_synapse_register_user_result.stdout
  failed_when: matrix_synapse_register_user_result.rc != 0 and 'User ID already taken' not in matrix_synapse_register_user_result.stdout
