session:
  name: authelia_session
  # secret is set by the env variables AUTHELIA_SESSION_SECRET_FILE
  #secret: unsecure_session_secret
  expiration: 3600  # 1 hour
  inactivity: 900  # 15 minutes
  domain: {{domain}}

authentication_backend:
  ldap:
    implementation: custom
    address: ldap://ldap:{{ldap_port}}
    timeout: 5s
    start_tls: false
    base_dn: {{ldap_domain}}
    additional_users_dn: ou=people
    users_filter: '(&({username_attribute}={input})(objectClass=person))'
    additional_groups_dn: ou=groups
    groups_filter: '(&(member={dn})(objectClass=groupOfNames))'
    group_search_mode: 'filter'
    permit_referrals: false
    permit_unauthenticated_bind: false
    user: cn={{admin_user}},ou=people,{{ldap_domain}}
    password: "{{admin_password}}"
    attributes:
      distinguished_name: 'distinguishedName'
      username: 'cn'  # or uid ?
      display_name: 'displayName'
      mail: 'mail'
      member_of: 'memberOf'
      group_name: 'cn'

  # Password reset through authelia works normally.
  password_reset:
    disable: false

storage:
  encryption_key: {{authelia_storage_encryption_key}}
  local:
    path: /data/db.sqlite3

# rules should be set by docker labels so each service can control it's protection policy
access_control:
  networks:
  - name: internal
    networks:
    - '10.0.0.0/8'
    - '172.16.0.0/12'
    - '192.168.0.0/18'
  default_policy: one_factor

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

notifier:
  disable_startup_check: false
{% if "mail" in services %}
  smtp: # authelia requires STARTLS for SMTP connection
    username: {{admin_user}}
    password: {{admin_password}}
    address: 'smtp://mail:25'
    sender: {{admin_user}}@{{domain}}
{% else %}
  filesystem:
    filename: /config/notification.txt
{% endif %}
