---
- name: Backup openwisp
  ansible.builtin.include_role:
    name: lokal
    tasks_from: backup
  vars:
    app: openwisp
    postgres_db: "{{db_name_openwisp}}"
    postgres_user: "{{db_user_openwisp}}"
