- name: Create app directory
  ansible.builtin.file:
    path: "{{ project_root }}/fdroid/{{item}}"
    state: directory
  loop:
    - data
    - repomaker
    - repo

- name: Stop current app if it is already running
  ansible.builtin.shell:
    cmd: "docker-compose down"
    chdir: "{{ project_root }}/fdroid"
    removes: docker-compose.yml  # runs only when this file exists
  ignore_errors: yes # in case of corrupted docker-compose.yml this would interrupt the whole playbook

- name: Render config.yml
  ansible.builtin.template:
    src: "config.yml.j2"
    dest: "{{ project_root }}/fdroid/data/config.yml"

- name: Render docker-compose.yml
  ansible.builtin.template:
    src: "compose.yml.j2"
    dest: "{{ project_root }}/fdroid/docker-compose.yml"
    mode: "0600"

- name: "Create repo signing key if it doesn't exist"
  ansible.builtin.shell:
    cmd: >
      docker-compose run --entrypoint keytool fdroid -genkey -v
      -keystore signing_key.keystore -alias fdroid -keyalg RSA -keysize 2048 -validity 10000 
      -storepass {{password_fdroid}} -keypass {{password_fdroid}} 
      -dname "cn={{domain}}, o={{project_name}}, c=Unknown"
    creates: "{{project_root}}/fdroid/data/signing_key.keystore"
    chdir: "{{project_root}}/fdroid"

- name: "Initialize with public f-droid repository"
  ansible.builtin.shell:
    cmd: git clone --depth 1 https://gitlab.com/fdroid/fdroiddata.git/ repo
    creates: "{{project_root}}/fdroid/data/repo"
    chdir: "{{project_root}}/fdroid"
  when: sync_repo_fdroid

- name: Docker-compose up
  ansible.builtin.shell: 
    cmd: "docker-compose up -d fileserver"
    chdir: "{{ project_root }}/fdroid"
