qpixel_community_name: Lokal community
qpixel_domain: "{{qpixel_subdomain}}.{{domain}}"
qpixel_mysql: "qpixel"
qpixel_mysql_user: qpixel
qpixel_mysql_password: Qpixel678423
qpixel_minio_user: "qpixel"
qpixel_minio_password: Qpixel678423
qpixel_minio_bucket: "qpixel"
qpixel_version: 2024.3.1
qpixel_subdomain: qpixel