---
- name: Install Resourcespace
  ansible.builtin.include_role:
    name: lokal
    tasks_from: install
  vars:
    app: resourcespace
    mysql_db: "{{mysql_database_resourcespace}}"
    mysql_user: "{{mysql_user_resourcespace}}"
    mysql_password: "{{mysql_password_resourcespace}}"
    data_dirs:
    - data
