---
- name: Remove resourcespace
  ansible.builtin.include_role:
    name: common
    tasks_from: remove
  vars:
    app: resourcespace
    mysql_db: '{{mysql_database_resourcespace}}'
    mysql_user: '{{mysql_user_resourcespace}}'
    mysql_password: '{{mysql_password_resourcespace}}'
