
# Container Secrets
acme_email: 
staging_acme: false
traefik_basicauth_users: ''
static_certificate:

# Subdomains
subdomain_traefik: router
subdomain_netdata: monitor
subdomain_prometheus: metrics
subdomain_grafana: dash
subdomain_mailhog: mailhog
subdomain_transmission: torrent
subdomain_portainer: portainer
