
# Container Secrets
acme_email: 
traefik_basicauth_users: ''


# Subdomains
subdomain_traefik: router
subdomain_netdata: monitor
subdomain_prometheus: metrics
subdomain_grafana: dash
subdomain_mailhog: mailhog
subdomain_kiwix: learn
subdomain_transmission: torrent
subdomain_portainer: portainer
subdomain_jellyfin: video
