---
- name: Install papad
  include_role:
    name: common
    tasks_from: install
  vars:
    app: papad
    data_dirs:
    - db
    - minio
    - nginx
    - tasks
    postgres_db: "{{db_name_papad}}"
    postgres_user: "{{db_user_papad}}"
    postgres_password: "{{db_password_papad}}"
    firewall_tcp:
    - "9001"
    start: false

- name: Copy nginx configs
  ansible.builtin.copy:
    src: "files/nginx/"
    dest: "{{app_root}}/nginx/"

- name: Copy tasks files
  ansible.builtin.copy:
    src: "files/tasks/"
    dest: "{{app_root}}/tasks/"

- name: Render config template
  ansible.builtin.template:
    src: service_config.env
    dest: "{{app_root}}/service_config.env"

# This is the command to start your app manually
- name: Start the app
  ansible.builtin.shell: 
    cmd: docker-compose up -d
    chdir: "{{app_root}}"