- name: Create app directory
  ansible.builtin.file:
    path: "{{ project_root }}/calibre/{{item}}"
    state: directory
  loop:
  - "server"
  - "web"
  - "data"

- name: Render docker-compose.yml
  ansible.builtin.template:
    src: "compose.yml.j2"
    dest: "{{ project_root }}/calibre/docker-compose.yml"
    mode: "0600"

- name: Docker-compose up
  ansible.builtin.shell: "docker-compose up -d"
  args:
    chdir: "{{ project_root }}/calibre/"
