---
- name: Install auth
  include_role:
    name: lokal
    tasks_from: install
  vars:
    app: auth
    data_dirs:
    - conf
    - data
    start: false

- name: Render authelia conf
  template:
    src: authelia.yml.j2
    dest: '{{app_root}}/conf/configuration.yml'

- name: Docker-compose up
  ansible.builtin.shell: 
    cmd: "docker compose up -d"
    chdir: "{{app_root}}"