---
- name: "Create app dir"
  ansible.builtin.file:
    path: "{{project_root}}/nextcloud/{{item}}"
    state: directory
  loop:
    - "data"
    - "config"

- name: "Init database"
  community.mysql.mysql_db:
    name: "{{mysql_database_nextcloud}}"
    login_user: root
    login_password: "{{mysql_root_password}}"
    login_host: localhost
    state: present

- name: "Grant user privileges to the DB"
  community.mysql.mysql_user:
    name: "{{mysql_user_nextcloud}}"
    password: "{{mysql_password_nextcloud}}"
    priv: "{{mysql_database_nextcloud}}.*:ALL"
    host: '%'
    state: present
    login_user: root
    login_password: "{{mysql_root_password}}"
    login_host: localhost

- name: "Render the docker-compose file"
  ansible.builtin.template:
    name: compose.yml.j2
    dst: "{{project_root}}/nextcloud/docker-compose.yml"

- name: Docker-compose up
  ansible.builtin.shell:
    cmd: "docker-compose up -d"
    chdir: "{{ project_root }}/nextcloud"
