---
- name: "Create app dir"
  ansible.builtin.file:
    path: '{{item}}'
    state: directory
  loop:
    - "{{data_dir_nextcloud}}"
    - "{{config_dir_nextcloud}}"

- name: "Init database"
  community.mysql.mysql_db:
    name: {{mysql_database_nextcloud}}
    login_user: root
    login_password: "{{mysql_root_password}}"
    login_host: localhost
    state: present

- name: "Grant user priviledges to the DB"
  community.mysql.mysql_user:
    name: {{mysql_user_nextcloud}}
    password: "{{mysql_password_nextcloud}}"
    priv: '{{mysql_database_nextcloud}}.*:ALL'
    state: present
    login_user: root
    login_password: "{{mysql_root_password}}"
    login_host: localhost

- name: "Render the docker-compose file"
  template:
    name: compose.yml.j2
    dst: '{{project_root}}/nextcloud/docker-compose.yml'

- name: Docker-compose up
  shell: "docker-compose up -d"
  args:
    chdir: "{{ project_root }}/nextcloud/"
