# Mandatory settings
# admin_password
# admin_email
# domain
debug: false
admin_user: admin

# Common base settings
project_name: Lokal
project_root: "/opt/lokal"
backup_root: "/opt/lokal-backup"
country: US
lang: en_US
locale: en_US.utf-8  # cs_CZ.utf8
ssh_port: 22
verbose: false
services: []

# HTTPS certificate handling
ssl_use_acme: false # obtain HTTPS certificates from ACME server
staging_acme: false # use only staging ACME server
# ssl_key:
# ssl_cert:

# cert resolver can be "dns", "http", or "tls"
cert_resolver: http

# If you are using "cert_resolver: dns" then you need to give API access to
# your DNS (domain) provider so the cert resolver can create domains and certificates
dns_provider: namecheap
namecheap_api_user:
namecheap_api_key:

# Common services settings
mysql_root_password: "{{'mysql' + lokal_secret | hash('sha1') | regex_search('\\w{8}') }}"
mysql_host: mariadb
mysql_port: 3306
postgres_root_password: "{{'postgres' + lokal_secret | hash('sha1') | regex_search('\\w{8}') }}"
postgres_host: postgres
postgres_port: 5432

# Common runtime variables
# UID: ''{{ ansible_facts["user_uid"] }}''
# GID: '{{ ansible_facts["user_gid"] }}'
# TZ: '{{ ansible_facts["date_time"]["tz"] }}'

# Empty defaults for the firewall
firewall_tcp: []
firewall_udp: []
firewall: false

version_prometheus: "latest" # v2.40.6
version_traefik: "latest" # v2.9.6
version_grafana: "latest" # 9.3.2
version_mariadb: "10.6.16-focal"
version_postgres: "16-3.4"

subdomain_traefik: router
subdomain_prometheus: metrics
subdomain_portainer: containers