project_name: vnet
project_root: "$HOME/lokal"
domain: vnet.lan
lang: en_US
locale: en_US.utf-8

# develop - uses mock email client and so on
# staging - like production but without TLS
deployment_environment: develop  # develop, staging, production
server_is_live: false

# Container Secrets
acme_email: 
acme_certs_dir: /media/certs/
traefik_basicauth_users: ''

dns_provider: namecheap
cert_resolver: dns
namecheap_api_user:
namecheap_api_key:

# Container Variables
# PUID: ''{{ ansible_facts["user_uid"] }}''
# PGID: '{{ ansible_facts["user_gid"] }}'
# TZ: '{{ ansible_facts["date_time"]["tz"] }}'
docker_pgid: $(grep docker /etc/group | cut -d ':' -f 3)
subdomain_traefik: router
subdomain_netdata: monitor
subdomain_prometheus: metrics
subdomain_grafana: dash
subdomain_mailhog: mailhog
subdomain_kiwix: learn
subdomain_transmission: torrent
subdomain_portainer: portainer
subdomain_jellyfin: video
# kiwix_data_dir: ${project_root}/config/services/kiwix/data
# transmission_config_dir: ${project_root}/config/services/transmission/config
# transmission_downloads_dir: ${project_root}/config/services/transmission/downloads
# transmission_watch_dir: ${project_root}/config/services/transmission/watch

# jellyfin_config_dir: ${project_root}/config/services/jellyfin/config
# jellyfin_data_dir: ${project_root}/config/services/jellyfin/data

# Application Secrets
mysql_root_password: default

# Application Variables
mysql_host: mariadb
mysql_port: 3601

# TO BE SEPARATED TO STANDALONE PLAYS
# Cloud Provider Secrets
hcloud_token:
vagrant_ip: 10.180.0.102

## Cloud Provider Variables
# primary_ssh_user: ubuntu # replace with ansible_user
hcloud_image: ubuntu-20.04
hcloud_location: nbg1
hcloud_server_type: cpx11
