---
- name: Create app directory
  file:
    path: "{{ project_root }}/unifi/data"
    state: directory

- name: Render docker-compose.yml
  ansible.builtin.template:
    src: "compose.yml.j2"
    dest: "{{ project_root }}/unifi/docker-compose.yml"
    mode: "0600"

- name: Docker-compose up
  shell: "docker-compose up -d unifi-poller unifi-controller"
  args:
    chdir: "{{ project_root }}/unifi/"
