---
- name: Install Unifi
  include_role:
    name: lokal
    tasks_from: install
  vars:
    app: unifi
    data_dirs:
    - data
    firewall_tcp:
    - 8080
    - 6789
    firewall_udp:
    - 3478
    - 10001
    - 1900
    - 5514
