#!/usr/bin/env bash
set -euf -o pipefail

CREATE USER IF NOT EXISTS '${MYSQL_USER_NEXTCLOUD}'@'%%' IDENTIFIED BY '${MYSQL_PASSWORD_NEXTCLOUD}';\n\
CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE_NEXTCLOUD};\n\
GRANT ALL ON \`${MYSQL_DATABASE_NEXTCLOUD}\`.* TO '${MYSQL_USER_NEXTCLOUD}'@'%%';\n\

FLUSH PRIVILEGES;\n\
" | dc exec -T mariadb mysql -p${MYSQL_ROOT_PASSWORD}
