- name: Create app directory
  ansible.builtin.file:
    path: "{{ project_root }}/kiwix/{{item}}"
    state: directory
  loop:
  - library
  - data

- name: Init empty library file
  ansible.builtin.copy:
    content: library.xml.tpl
    dest: "{{ project_root }}/kiwix/library/library.xml"
    force: false

- name: Render docker-compose.yml
  ansible.builtin.template:
    src: "compose.yml.j2"
    dest: "{{ project_root }}/kiwix/docker-compose.yml"
    mode: "0600"

- name: Docker-compose up
  ansible.builtin.shell: 
    cmd: "docker-compose start"
    chdir: "{{ project_root }}/kiwix"
