- name: Find downloaded zim files
  ansible.builtin.shell:
    cmd: >
      docker-compose exec kiwix 
      find /downloads/complete -name '*.zim' | xargs
    chdir: "{{project_root}}/kiwix"
  register: zims

- name: Update library with transmission-downloaded zim files
  ansible.builtin.shell:
    cmd: >
      docker-compose exec kiwix 
      kiwix-manage /library/library.xml add {{zims.stdout}}
    chdir: "{{project_root}}/kiwix"
  when: zims.stdout

- name: Restart kiwix service
  ansible.builtin.shell:
    cmd: docker-compose restart kiwix 
    chdir: "{{project_root}}/kiwix"
