---
- name: Does {{app}} PostgreSQL already exist?
  ansible.builtin.shell:
    cmd: >
      docker compose exec postgres
      psql -XtAc "SELECT 1 FROM pg_database WHERE datname='{{postgres_db}}'" postgres postgres
    chdir: "{{project_root}}/lokal"
  register: psql_db_exists

- name: Create {{app}} PostgreSQL user
  ansible.builtin.shell:
    cmd: >
      docker compose exec postgres
      psql -c "CREATE USER {{postgres_user}} WITH NOSUPERUSER NOCREATEDB PASSWORD '{{postgres_password}}'" postgres postgres;
    chdir: "{{project_root}}/lokal"
  when: psql_db_exists.stdout is falsy

- name: Create {{app}} PostgreSQL database
  ansible.builtin.shell:
    cmd: >
      docker compose exec postgres
      psql -c "CREATE DATABASE {{postgres_db}} OWNER {{postgres_user}}" postgres postgres;
    chdir: "{{project_root}}/lokal"
  when: psql_db_exists.stdout is falsy

- name: Create extensions for {{app}} in PostgreSQL
  ansible.builtin.shell:
    cmd: >
      docker compose exec postgres
      psql -c "CREATE EXTENSION IF NOT EXISTS {{item}}" {{postgres_db}} postgres;
    chdir: "{{project_root}}/lokal"
  when: postgres_extensions is defined
  loop: "{{postgres_extensions}}"
