---
- name: Install moodle
  ansible.builtin.include_role:
    name: lokal
    tasks_from: install
  vars:
    app: moodle
    data_dirs:
    - app
    - data
    - db
    # no db because moodle's container creates DB on its own
    start: true