---
- name: Ensure base dirs exist"
  ansible.builtin.file:
    path: '{{item}}'
    state: directory
    owner: '{{ansible_user}}'
  loop:
    - "{{project_root}}"
    - "{{backup_root}}"
  become: yes
  when: "not backup is defined and not restore is defined and not update is defined"
  notify:
  - Restart router

- name: Register uid and gid variables
  set_fact:
    uid: '{{ansible_facts["user_uid"]}}'
    gid: '{{ansible_facts["user_gid"]}}'
    tz: '{{ ansible_facts["date_time"]["tz"] }}'
