version: "2.1"
services:
  calibre:
    image: linuxserver/calibre-web
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data-calibre-web:/config
      - ./library:/library
    restart: unless-stopped
  calibre-server:
    image: linuxserver/calibre
    container_name: calibre-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data-calibre-server:/config
      - ./library:/config/Calibre Library
    restart: unless-stopped
networks:
  default:
    external:
      name: vpuu-offline