version: "2.1"
services:
  calibre:
    image: linuxserver/calibre-web
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data:/config
      - ./library:/library
    restart: unless-stopped
networks:
  default:
    external:
      name: vpuu-offline