# Prepare the most basic things
- name: "Creating project root directory"
  ansible.builtin.file:
    state: directory
    path: '{{project_root}}'

- name: Render base compose.yml
  ansible.builtin.template:
    src: compose.yml.j2
    dest: '{{project_root}}/base.yml'

- name: Create app dirs
  ansible.builtin.file:
    path: '{{project_root}}/{{item}}/data'
    state: directory
  loop:
    - mysql
    - traefik
    - grafana
    - prometheus
    - portainer
    - transmission
    - jellyfin

- name: "Self signed certs"
  include_tasks:
    file: self-signed-certs.yml
  when: not server_is_live

- name: "Setup traefik"
  include_tasks:
    file: setup-traefik.yml

- name: "Setup prometheus"
  include_tasks:
    file: setup-prometheus.yml
