---
- name: Create app dirs
  ansible.builtin.file:
    path: '{{project_root}}/{{item}}/data'
    state: directory
  loop:
    - mysql
    - traefik
    - grafana
    - prometheus
    - portainer
    - transmission
    - jellyfin

- name: "Setup traefik"
  include_tasks:
    file: setup-traefik.yml

- name: "Setup prometheus"
  include_tasks:
    file: setup-prometheus.yml

- name: "Install necessary base software"
  package:
    name:
      - python3-pymysql
    state: present
  become: true

- name: Render base docker-compose.yml
  ansible.builtin.template:
    src: compose.yml.j2
    dest: '{{project_root}}/docker-compose.yml'

- name: Docker-compose up
  ansible.builtin.shell: 
    cmd: "docker-compose up -d"
    chdir: "{{project_root}}"
