
- name: Ensure primary user is created and added to sudo group
  user:
    name: "{{ primary_ssh_user }}"
    shell: /bin/bash
    groups:
      - sudo
    append: yes
    createhome: yes
  register: primary_ssh_user_params

- name: Ensure sudo users can issue commands without specifying password
  copy:
    content: '%sudo ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/sudo
    mode: 0600

- name: Register root ssh user's details
  user:
    name: "{{ root_ssh_user }}"
  register: root_ssh_user_params
  when: "{{ setup_ssh | default(false) }}"

- set_fact:
    authorized_keys_src: "{{ root_ssh_user_params.home }}/.ssh/authorized_keys"
    authorized_keys_dest: "{{ primary_ssh_user_params.home }}/.ssh/authorized_keys"
  when: "{{ setup_ssh | default(false) }}"

- name: Harden ssh security
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^#?PermitEmptyPasswords'
      line: 'PermitEmptyPasswords no'
    - regexp: '^#?PermitRootLogin'
      line: 'PermitRootLogin no'
    - regexp: '^(#\s*)?PasswordAuthentication '
      line: 'PasswordAuthentication no'
  when: "{{ setup_ssh | default(false) }}"

- name: restart sshd
  service:
    name: ssh
    state: restarted
  when: "{{ setup_ssh | default(false) }}"

- name: Ensure that the primary user's ssh directory exists
  file:
    path: "{{ primary_ssh_user_params.home }}/.ssh"
    state: directory
    owner: "{{ primary_ssh_user }}"
    group: "{{ primary_ssh_user }}"
    mode: 0700
  when: "{{ setup_ssh | default(false) }}"

- name: Ensure authorized_keys file is initiated for primary user
  copy:
    content: ""
    dest: "{{ primary_ssh_user_params.home }}/.ssh/authorized_keys"
    group: "{{ primary_ssh_user }}"
    owner: "{{ primary_ssh_user }}"
    mode: 0600
  when: "{{ setup_ssh | default(false) }}"

- name: Install sync_authorized_keys service unit file
  template:
    src: sync_authorized_keys.service.j2
    dest: /etc/systemd/system/sync_authorized_keys.service
  when: "{{ setup_ssh | default(false) }}"

- name: Start/Enable sync_authorized_keys service unit file
  systemd:
    name: sync_authorized_keys.service
    enabled: yes
    state: started
  when: "{{ setup_ssh | default(false) }}"
