- name: Make acme certs directory if it does not yet exist
  become: yes
  become_user: root
  file:
    path: "{{ acme_certs_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  when: not server_is_live

- name: Make acme certs directory if it does not yet exist
  become: yes
  become_user: root
  file:
    path: "{{ acme_certs_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  when: not server_is_live

- name: Change file ownership, group and permissions
  become: yes
  become_user: root
  ansible.builtin.copy:
    src: "/tmp/{{ acme_domain }}/{{ item }}"
    dest: "{{ acme_certs_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - "{{ acme_domain }}.cer"
    - "{{ acme_domain }}.key"
  when: not server_is_live