---
- name: Make acme certs directory if it does not yet exist
  become: yes
  become_user: root
  file:
    path: "{{ acme_certs_dir }}"
    state: directory
    mode: 0700

- name: Ensure SSL private key
  become: yes
  become_user: root
  community.crypto.openssl_privatekey:
    path: "{{ acme_certs_dir }}/{{domain}}.key"

- name: Create SSL CSR
  become: yes
  become_user: root
  community.crypto.openssl_csr:
    path: "{{ acme_certs_dir }}/{{domain}}.csr"
    privatekey_path: "{{ acme_certs_dir }}/{{domain}}.key"
    organization_name: "Wakoma"
    commonName: "{{domain}}"
    email_address: "devel@wakoma.net"
    country_name: "US"

- name: Create SSL certificate
  become: yes
  become_user: root
  community.crypto.x509_certificate:
    provider: "selfsigned"
    path: "{{ acme_certs_dir }}/{{domain}}.cer"
    privatekey_path: "{{ acme_certs_dir }}/{{domain}}.key"
    csr_path: "{{ acme_certs_dir }}/{{domain}}.csr"
