
networks:
  traefik:
    external: true

services:
  website:
    image: jitesoft/lighttpd:1.4.76
    user: "{{uid}}:{{gid}}"  # run the container service as app user (not root)
    container_name: {{website_domain | replace(".", "-")}}
    environment:
      PORT: {{app_port}}
      SERVER_NAME: {{website_domain}}
      SERVER_ROOT: /var/www/html
      SKIP_HEALTHCHECK: false
      MAX_FDS: 1024
    volumes:
      # when using app_git - it will be checked out to app_root/app
      - {{app_root}}/{{app}}/{{website_dir}}:/var/www/html
    networks:
      - traefik
{% include "labels.yml" %}
