---
- name: Install Matomo
  include_role:
    name: lokal
    tasks_from: install
  vars:
    app: matomo
    mysql_user: "{{mysql_user_matomo}}"
    mysql_password: "{{mysql_password_matomo}}"
    mysql_db: "{{mysql_database_matomo}}"
    data_dirs:
    - data
