---
- name: Remove matomo
  ansible.builtin.include_role:
    name: lokal
    tasks_from: remove
  vars:
    app: matomo
    mysql_db: "{{mysql_database_matomo}}"
    mysql_user: "{{mysql_user_matomo}}"
