---
- name: Install jitsi
  ansible.builtin.include_role:
    name: common
    tasks_from: install
  vars:
    app: jitsi
    mysql_user: '{{mysql_user_jitsi}}'
    mysql_password: '{{mysql_password_jitsi}}'
    mysql_db: '{{mysql_database_jitsi}}'
    data_dirs:
    - web
    - transcripts
    - prosody
    - prosody-plugins-custom
    - jicofo
    - jvb