networks:
  traefik:
    name: traefik
  mysql:
    name: mysql
  prometheus:
    name: prometheus
  postgres:
    name: postgres
  lokal:
    name: lokal
    internal: true
  minio:
    name: minio

services:
  mariadb:
    container_name: "{{mysql_host}}"
    image: mariadb:{{version_mariadb}}
    user: "{{uid}}:{{gid}}"  # run the container service as app user (not root)
    environment:
      MYSQL_ROOT_PASSWORD: "{{mysql_root_password}}"
      MARIADB_MYSQL_LOCALHOST_USER: "true"
    networks:
    - mysql
    - lokal
    healthcheck:
      test: mysql --protocol tcp -u root --password={{mysql_root_password}} -e "SELECT 1 FROM DUAL" mysql
      interval: 60s
      retries: 5
      start_period: 5s
      timeout: 1s
    restart: unless-stopped
    volumes:
    - "{{lokal_root}}/mariadb/:/var/lib/mysql/"

  postgres:
    container_name: postgres
    image: nickblah/postgis:12-bullseye-postgis-3
    # user: "{{uid}}:{{gid}}"  # needs the postgres user
    environment:
      POSTGRES_PASSWORD: "{{postgres_root_password}}"
      DEFAULT_COLLATION: "{{locale}}"
      DEFAULT_CTYPE: "{{locale}}"
    networks:
    - postgres
    - lokal
    restart: unless-stopped
    volumes:
    - "{{lokal_root}}/postgres/:/var/lib/postgres/data/"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:{{version_prometheus}}
    user: "{{uid}}:{{gid}}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.prometheus.entrypoints: websecure
      traefik.http.routers.prometheus.rule: Host(`{{subdomain_prometheus}}.{{domain}}`)
      traefik.http.routers.prometheus.tls: "true"
      traefik.http.services.prometheus.loadbalancer.server.port: 9090
      traefik.http.routers.prometheus.middlewares: admin-auth@file
{% if ssl_use_acme %}
      traefik.http.routers.prometheus.tls.certresolver: {{cert_resolver}}
{% endif %}
    networks:
    - traefik
    - lokal
    restart: unless-stopped
    volumes:
    - {{lokal_root}}/prometheus/etc/prometheus/:/etc/prometheus/
    - {{lokal_root}}/prometheus/data/:/prometheus/
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    user: "{{uid}}:{{gid_docker}}"
    restart: unless-stopped
    command: --admin-password '{{admin_password|password_hash('bcrypt')}}'
    security_opt:
    - no-new-privileges:true
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - "{{lokal_root}}/portainer/:/data/"
    networks:
    - prometheus
    - traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.entrypoints: websecure
      traefik.http.routers.portainer.rule: Host(`{{subdomain_portainer}}.{{domain}}`)
      traefik.http.routers.portainer.tls: "true"
      traefik.http.services.portainer.loadbalancer.server.port: 9000
{% if ssl_use_acme %}
      traefik.http.routers.portainer.tls.certresolver: {{cert_resolver}}
{% endif %}

  minio:
    user: "{{uid}}:{{gid}}"  # run the container service as app user (not root)
#   ports:
#   - "9000:9000"
#   - "9090:9090"
    environment:
      MINIO_ROOT_USER: {{admin_user}}
      MINIO_ROOT_PASSWORD: "{{admin_password}}"
      MC_CONFIG_DIR: /.mc
    volumes:
      - "{{lokal_root}}/minio/data:/data"
      - "{{lokal_root}}/minio/config:/.mc"
    image: quay.io/minio/minio
    command: server /data --console-address=":9090"
    container_name: minio
    networks:
    - minio
    - lokal

  traefik:
    image: traefik:{{version_traefik}}
    container_name: traefik
    # cannot be simply app_user:app_user because of root:docker privileges on /var/run/docker.sock
    user: "{{uid}}:{{gid_docker}}"  # run the container service as app user (not root)
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.rule: Host(`{{subdomain_traefik}}.{{domain}}`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.tls: "true"
      traefik.http.services.traefik.loadbalancer.server.port: 8080
      traefik.http.routers.traefik.middlewares: admin-auth@file
{% if ssl_use_acme %}
      traefik.http.routers.traefik.tls.certresolver: {{cert_resolver}}
{% endif %}
    networks:
    - traefik
    ports:
    - 80:80
    - 443:443
#    - 465:465
#    - 993:993
    - 8448:8448
    restart: unless-stopped
    environment:
      CERT_RESOLVER: {{cert_resolver}}
{% if cert_resolver == "dns" and dns_provider == "namecheap" %}
      NAMECHEAP_API_USER: {{namecheap_api_user}}
      NAMECHEAP_API_KEY: {{namecheap_api_key}}
{% endif %}
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - "{{lokal_root}}/traefik/log:/var/log"  # used for fail2ban
    - "{{lokal_root}}/traefik/acme:/acme"
{% if not ssl_use_acme %}
    - "{{project_root}}/.certs/{{domain}}/:/certs/"
{% endif %}
    - "{{lokal_root}}/traefik/conf:/config"
    command:
    - --accessLog=true
    - --api.insecure=false
    - --api.dashboard=true
    - --api.debug=false
{% if ssl_use_acme %}
    - --certificatesResolvers.dns.acme.dnsChallenge.delayBeforeCheck=60
    - --certificatesResolvers.dns.acme.dnsChallenge.provider={{dns_provider}}
    - --certificatesResolvers.dns.acme.email={{admin_email}}
    - --certificatesResolvers.dns.acme.storage=/acme/acme.json
    - --certificatesresolvers.http.acme.httpchallenge=true
    - --certificatesresolvers.http.acme.httpchallenge.entrypoint=web
    - --certificatesresolvers.http.acme.email={{admin_email}}
    - --certificatesresolvers.http.acme.storage=/acme/acme.json
{% if staging_acme %}
    - --certificatesresolvers.http.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
{% endif %}
    - --certificatesresolvers.tls.acme.tlschallenge=true
    - --certificatesresolvers.tls.acme.email={{admin_email}}
    - --certificatesresolvers.tls.acme.storage=/acme/acme.json
{% if staging_acme %}
    - --certificatesresolvers.tls.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
{% endif %}
{% endif %}
    - --entrypoints.web.address=:80
    - --entrypoints.websecure.address=:443/tcp
    - --entryPoints.federation.address=:8448
    - --entryPoints.metrics.address=:8082
#    - --entryPoints.smtp.address=:465  # do not bind those port - the mail container do this on its own
#    - --entryPoints.imap.address=:993  # do not bind those port - the mail container do this on its own
    - --entrypoints.web.http.redirections.entryPoint.to=websecure
    - --entrypoints.web.http.redirections.entryPoint.scheme=https
    - --entrypoints.web.http.redirections.entrypoint.permanent=true
    ## Please see the Forwarded Header Trust section of the Authelia Traefik Integration documentation.
    - --entryPoints.websecure.forwardedHeaders.trustedIPs=10.0.0.0/8,172.16.0.0/16,192.168.0.0/16,fc00::/7
#   - --entryPoints.websecure.forwardedHeaders.insecure=false
    - --entryPoints.websecure.proxyProtocol.trustedIPs=10.0.0.0/8,172.16.0.0/16,192.168.0.0/16,fc00::/7
    # - --entryPoints.websecure.proxyProtocol.insecure=false
    - --log.level=WARNING
    - --accessLog.filePath=/var/log/access.log
    - --accessLog.filters.statusCodes=400-505
    - --metrics.prometheus=true
    - --metrics.prometheus.buckets=0.100000, 0.300000, 1.200000, 5.000000
    - --metrics.prometheus.addEntryPointsLabels=true
    - --metrics.prometheus.addServicesLabels=true
    - --metrics.prometheus.entryPoint=metrics
    - --providers.docker=true
    - --providers.docker.endpoint=unix:///var/run/docker.sock
    - --providers.docker.exposedbydefault=false
    - --providers.docker.network=traefik
    - --serversTransport.insecureSkipVerify=true
    - --providers.file.directory=/config
    - --providers.file.watch=true
    # - --tls.domains={{domain}}

{% if ssl_use_acme %}
  dumper:
    image: ldez/traefik-certs-dumper:v2.8.1
    container_name: dumper
    command: file --version v2 --watch --source /data/acme.json --dest /dump --post-hook "sh /hook.sh"
    restart: unless-stopped
    user: "{{uid}}:{{gid}}"
    labels:
      traefik.enable: false
    volumes:
      - {{lokal_root}}/traefik/acme:/data
      - {{lokal_root}}/traefik/dump:/dump
      - {{project_root}}/.certs:/lokal
      - {{lokal_root}}/dumper/hook.sh:/hook.sh
{% endif %}

  fail2ban:
    image: crazymax/fail2ban:latest
    # no user: "{{uid}}:{{gid}}" because it cannot bind socket /var/run/fail2ban/fail2ban.sock
    container_name: fail2ban
    network_mode: "host"
    depends_on:
    - traefik
    cap_add:
    - NET_ADMIN
    - NET_RAW
    volumes:
    - {{lokal_root}}/traefik/log/:/var/log/traefik/:ro
    - {{lokal_root}}/fail2ban/:/data/
