---
- name: Install mail
  ansible.builtin.include_role:
    name: lokal
    tasks_from: install
  vars:
    app: mail
    app_version: 0.7
    app_domain: "mail.{{domain}}"
    app_db: mysql
    app_templates:
      maddy.conf:  mail/maddy.conf
    app_dirs:
    - mail
    - webmail
    - log
