---
- name: Install base
  ansible.builtin.include_role:
    name: lokal
    tasks_from: install
  vars:
    app: mail
    app_version: 0.7
    app_domain: "mail.{{domain}}"
    mysql_db: cypht
    mysql_user: cypht
    mysql_password: cypht
    data_dirs:
    - mail
    - webmail
    - log
    firewall_tcp:
    - 465
    - 993
    start: false

- name: Render maddy mail config
  ansible.builtin.template:
    src: maddy.conf
    dest: "{{app_root}}/mail/maddy.conf"

- name: Docker-compose up
  ansible.builtin.shell:
    cmd: "docker compose up -d"
    chdir: "{{app_root}}"
