---
- name: Install base
  ansible.builtin.include_role:
    name: lokal
    tasks_from: install
  vars:
    app: mail
    app_version: 0.7
    app_domain: "mail.{{domain}}"
    mysql_db: cypht
    mysql_user: cypht
    mysql_password: cypht
    data_dirs:
    - data
    firewall_tcp:
    - 465
    - 993
    start: false

- name: Self-sign certificate for the mail.domain
  ansible.builtin.import_tasks:
    file: "roles/lokal/tasks/include/generate-self-signed-certs.yml"
  vars:
    cert_domain: "mail.{{domain}}"
  when: not ssl_use_acme and not (ssl_key is defined and ssl_cert is defined)

- name: Render maddy mail config
  ansible.builtin.template:
    src: maddy.conf
    dest: "{{app_root}}/data/maddy.conf"

- name: Docker-compose up
  ansible.builtin.shell:
    cmd: "docker compose up -d"
    chdir: "{{app_root}}"
