- name: Install mail
  ansible.builtin.include_role:
    name: lokal
    tasks_from: install
  vars:
    app: mail
    data_dirs:
    - data
    - state
    - logs
    - config
    firewall_tcp:
      # - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    start: false

- name: Render mail conf
  template:
    src: mailserver.env.j2
    dest: '{{app_root}}/mailserver.env'

- name: Docker-compose up
  ansible.builtin.shell: 
    cmd: "docker compose up -d"
    chdir: "{{app_root}}"