tls:
  options:
    default:
      minVersion: VersionTLS12
    mintls13:
      minVersion: VersionTLS13

  stores:
    default:
      defaultCertificate:
        certFile: /certs/local.crt
        keyFile: /certs/local.key

http:
  services:
    vnet:
      loadBalancer:
        servers:
          - url: http://vpuu.org.za/ict4d/v-net-bringing-internet-connectivity-into-low-income-areas
