http:
  middlewares:
    admin-auth:
      basicAuth:
        users:
          - "{{admin_user}}:{{admin_password|password_hash('bcrypt')}}"

{% if not ssl_use_acme %}
tls:
  options:
    default:
      minVersion: VersionTLS12
    mintls13:
      minVersion: VersionTLS13
  stores:
    default:
      defaultCertificate:
        certFile: /certs/{{domain}}.crt
        keyFile: /certs/{{domain}}.key
{% endif %}
