---
- name: Install prometheus
  include_role:
    name: lokal.base.lokal
    tasks_from: install
  vars:
    app_version: prometheus_version
    app_dirs:
    - data
    - config
    app_files:
      "alert.yml": config/alert.yml
      "prometheus.yml": config/prometheus.yml
