---
- name: Export app_root variable
  ansible.builtin.set_fact:
    app_root: "{{project_root}}/{{app}}"

- name: Create {{app}} directory
  ansible.builtin.file:
    path: "{{app_root}}"
    state: directory

- name: Create {{app}} external data directories
  ansible.builtin.file:
    path: "{{item.value}}"
    state: directory
  loop: "{{linked_dirs | dict2items }}"
  when: linked_dirs is defined and linked_dirs is truthy

- name: Link {{app}} external directories
  ansible.builtin.file:
    path: "{{app_root}}/{{item.key}}"
    src: "{{item.value}}"
    state: link
  loop: "{{linked_dirs | dict2items }}"
  when: linked_dirs is defined and linked_dirs is truthy 

- name: Create {{app}} data directories
  ansible.builtin.file:
    path: "{{app_root}}/{{item}}"
    state: directory
  loop: "{{data_dirs}}"
  when: data_dirs is defined

- name: Get previous {{app}} version
  ansible.builtin.slurp:
    src: "{{app_root}}/version"
  register: version_file
  when: app_version is defined
  ignore_errors: true

- name: Parse previous {{app}} version
  ansible.builtin.set_fact:
    app_version_prev: "{{version_file['content'] | b64decode}}"
    app_upgrade: "{{(version_file['content'] | b64decode) is version(app_version, '<')}}"
  when: app_version is defined and version_file is defined and version_file.content is defined

- name: Set current {{app}} version
  ansible.builtin.copy:
    dest: "{{app_root}}/version"
    content: "{{app_version}}"
  when: app_version is defined
   
- name: Init {{app}} MySQL database
  community.mysql.mysql_db:
    name: "{{mysql_db}}"
    login_user: root
    login_password: "{{mysql_root_password}}"
    login_port: "{{mysql_port}}"
    state: present
  when: mysql_db is defined

- name: Grant {{app}} user privileges to the new MySQL db
  community.mysql.mysql_user:
    name: "{{mysql_user}}"
    password: "{{mysql_password}}"
    priv: '{{mysql_db}}.*:ALL'
    host: '%'
    state: present
    login_user: root
    login_password: "{{mysql_root_password}}"
    login_port: "{{mysql_port}}"
  when: mysql_db is defined

- name: Create new {{app}} PostgreSQL user
  community.postgresql.postgresql_user:
    name: "{{postgres_user}}"
    password: "{{postgres_password}}"
    login_host: localhost
    login_password: "{{postgres_root_password}}"
    login_port: "{{postgres_port}}"
  when: postgres_db is defined

- name: Create new {{app}} PostgreSQL database for the user
  community.postgresql.postgresql_db:
    name: "{{postgres_db}}"
    login_host: localhost
    login_password: "{{postgres_root_password}}"
    login_port: "{{postgres_port}}"
    owner: "{{postgres_user}}"
    state: present
  when: postgres_db is defined

- name: Allow {{app}} firewall ports
  become: true
  vars:
    firewall_group: "{{app}}"
    firewall_allowed_tcp_ports: "{{firewall_tcp}}"
    firewall_allowed_udp_ports: "{{firewall_udp}}"
  ansible.builtin.import_role:
    name: geerlingguy.firewall.d
  when: firewall_tcp is truthy or firewall_udp is truthy
  # We need to reload docker so it places all its iptables rules back since the
  # firewall restart blindly flushes all firewall chains (even DOCKER chains)
  notify: Reload docker

- name: Render {{app}} docker-compose.yml
  ansible.builtin.template:
    src: "compose.yml.j2"
    dest: "{{app_root}}/docker-compose.yml"
    mode: "0600"

# you can avoid starting the app defining "start: false" in `vars` section
- name: Docker-compose up
  ansible.builtin.shell: 
    cmd: docker compose up -d
    chdir: "{{app_root}}"
  when: not start is defined or start is truthy  # start only when start: false is not a fact
  notify: Restart router

- name: Docker purge unused images
  ansible.builtin.shell: 
    cmd: docker image prune -f
    chdir: "{{app_root}}"
  when: app_version is defined and app_upgrade is defined and app_upgrade is truthy