#######################
# glauth-ui-light.conf

# dbfile: glauth conf file
#    with watchconfig enabled for hot-reload on conf file change
#    glauth-ui-light need write access
dbfile = "/app/ldap/db.cfg"

# run on a non privileged port
port = "0.0.0.0:8080"
# When a self hosted ssl reverse proxy is used :
#  port = "127.0.0.1:8080"

# Custom first page texts
appname = "Lokal"
appdesc = "Manage users and groups for glauth ldap server"

# Simplfy amdin ui when no need for otp
maskotp = false

# optional default unix fields
defaulthomedir = "/home"
defaultloginshell = "/bin/false"

[sec]
  # TODO set random secrets for CSRF token
  csrfrandom = "{{ lokal_secret }}"

[passpolicy]
  min = 2
  max = 24
  allowreadssha256 = true  # to be set to false when all passwords are bcrypt
  entropy = 60             # optional password constraint


[cfgusers]
  start = 5000           # start with this uid number
  admin = 5501        # members of this group are admins
  mail = 5502   # members of this group have mail account

[cfggroups]
  start = 5600   # start with this gid number