---
- name: Create app dirs
  ansible.builtin.file:
    path: '{{project_root}}/base/{{item}}'
    state: directory
  loop:
    - mysql
    - traefik
    - grafana
    - prometheus/data
    - portainer
    - transmission
    - postgres
    - mail
    - ldap
    - fail2ban/filter.d
    - fail2ban/jail.d

- name: Init IPTABLES firewall
  ansible.builtin.import_role:
    name: geerlingguy.firewall.d
  vars:
    firewall_state: started
    firewall_enabled_at_boot: true
    firewall_allowed_tcp_ports:
      # ssh
      - 22
      # web
      - 80
      - 443
      # mail
      - 465
      - 993
      # transmission
      - 9091
      - 51413
    firewall_allowed_udp_ports:
      # transmission
      - 51413
    firewall_disable_ufw: true
  become: true

- name: Reload docker
  shell:
    cmd: "systemctl reload docker"
  become: true

- name: Get certificates - key
  ansible.builtin.copy:
    src: "{{ssl_key}}"
    dest: "{{project_root}}/base/{{domain}}.key"
  when: not server_is_live and ssl_key is truthy and ssl_cert is truthy

- name: Get certificates - cert
  ansible.builtin.copy:
    src: "{{ssl_cert}}"
    dest: "{{project_root}}/base/{{domain}}.crt"
  when: not server_is_live and ssl_key is truthy and ssl_cert is truthy

- name: "Generate self-signed certs"
  include_tasks:
    file: include/generate-self-signed-certs.yml
  when: not server_is_live and ssl_key is falsy and ssl_cert is falsy

- name: "Render traefik configuration"
  ansible.builtin.template:
    src: traefik/dynamic.yml.j2
    dest: '{{project_root}}/base/traefik/conf/dynamic.yml'

- name: "Copy prometheus config"
  ansible.builtin.copy:
    src: files/prometheus
    dest: '{{project_root}}/base/prometheus/etc/'

- name: Render traefik fail2ban filter
  template:
    src: fail2ban/traefik-filter.conf.j2
    dest: '{{project_root}}/base/fail2ban/filter.d/traefik-filter.conf'

- name: Render traefik fail2ban jail
  template:
    src: fail2ban/traefik-jail.conf.j2
    dest: '{{project_root}}/base/fail2ban/jail.d/traefik.conf'

- name: Render mail conf
  template:
    src: mail/mailserver.env.j2
    dest: '{{project_root}}/base/mail/mailserver.env'

- name: Warn if a non-linux OS is used
  debug:
    msg: "You are installing Lokal on unsuported OS {{ansible_facts['system']}}!
      Make sure to have mysql client and python3-pymysql installed"
  when: ansible_facts['system'] != "Linux"

- name: "Install necessary base software"
  package:
    name:
      - mariadb-client
      - postgresql-client
      - python3-pymysql
      - python3-psycopg2
      - python3-passlib
    state: present
  become: true
  when: ansible_facts['system'] == "Linux" # disable on OSes without package managers

- name: "Force local MySQL client to connect via TCP"
  ansible.builtin.copy:
    dest: "$HOME/.my.cnf"
    content: "
  [client]\n
  protocol=tcp\n"

- name: Render base docker-compose.yml
  ansible.builtin.template:
    src: compose.yml.j2
    dest: '{{project_root}}/base/docker-compose.yml'

- name: Docker-compose up
  ansible.builtin.shell: 
    cmd: "docker-compose up -d"
    chdir: "{{project_root}}/base"

- name: Give the base time to boot up - takes at least 10 seconds
  ansible.builtin.pause:
    seconds: 10
