---
- name: Install base
  ansible.builtin.include_role:
    name: lokal
    tasks_from: install
  vars:
    app: base
    data_dirs:
    - ldap
    - mail
    - transmission
    firewall_tcp:
    - 465
    - 993
    - 9091
    - 51413
    firewall_udp:
    - 51413
    start: false

- name: Create ldap MySQL database
  ansible.builtin.include_tasks:
    file: roles/lokal/tasks/mysqldb/create.yml
  vars:
    mysql_db: ldap
    mysql_user: ldap
    mysql_password: ldap

- name: Render ldap config
  ansible.builtin.template:
    src: ldap/config.toml
    dest: '{{app_root}}/ldap/config.cfg'

- name: Render ldap config
  ansible.builtin.template:
    src: mail/mailserver.env
    dest: '{{app_root}}/mailserver.env'

- name: Docker-compose up
  ansible.builtin.shell:
    cmd: "docker compose up -d"
    chdir: "{{app_root}}"
