---
- name: Create app dirs
  ansible.builtin.file:
    path: '{{project_root}}/base/{{item}}/data'
    state: directory
  loop:
    - mysql
    - traefik
    - grafana
    - prometheus
    - portainer
    - transmission
    - postgres
    - mail

- name: Init IPTABLES firewall
  ansible.builtin.import_role:
    name: geerlingguy.firewall.d
  vars:
    firewall_state: started
    firewall_enabled_at_boot: true
    firewall_allowed_tcp_ports:
      # ssh
      - 22
      # web
      - 80
      - 443
      # mail
      - 465
      - 993
      # transmission
      - 9091
      - 51413
    firewall_allowed_udp_ports:
      # transmission
      - 51413
    firewall_disable_ufw: true
  become: true

- name: Reload docker
  shell:
    cmd: "systemctl reload docker"
  become: true

- name: "Setup traefik"
  include_tasks:
    file: include/setup-traefik.yml

- name: "Setup prometheus"
  include_tasks:
    file: include/setup-prometheus.yml

- name: Create traefik jail and filter dirs
  ansible.builtin.file:
    path: '{{project_root}}/base/fail2ban/data/{{item}}'
    state: directory
  loop:
    - jail.d
    - filter.d

- name: Render traefik fail2ban filter
  template:
    src: fail2ban/traefik-filter.conf.j2
    dest: '{{project_root}}/base/fail2ban/data/filter.d/traefik-filter.conf'

- name: Render traefik fail2ban jail
  template:
    src: fail2ban/traefik-jail.conf.j2
    dest: '{{project_root}}/base/fail2ban/data/jail.d/traefik.conf'

- name: Render mail conf
  template:
    src: mail/mailserver.env.j2
    dest: '{{project_root}}/base/mail/mailserver.env'
  when: not debug_smtp

- name: Warn if a non-linux OS is used
  debug:
    msg: "You are installing Lokal on unsuported OS {{ansible_facts['system']}}!
      Make sure to have mysql client and python3-pymysql installed"
  when: ansible_facts['system'] != "Linux"

- name: "Install necessary base software"
  package:
    name:
      - mariadb-client
      - postgresql-client
      - python3-pymysql
      - python3-psycopg2
    state: present
  become: true
  when: ansible_facts['system'] == "Linux" # disable on OSes without package managers

- name: "Force local MySQL client to connect via TCP"
  ansible.builtin.copy:
    dest: "$HOME/.my.cnf"
    content: "
  [client]\n
  protocol=tcp\n"

- name: Render base docker-compose.yml
  ansible.builtin.template:
    src: compose.yml.j2
    dest: '{{project_root}}/base/docker-compose.yml'

- name: Docker-compose up
  ansible.builtin.shell: 
    cmd: "docker-compose up -d"
    chdir: "{{project_root}}/base"

- name: Give the base time to boot up - takes at least 10 seconds
  ansible.builtin.pause:
    seconds: 10
