networks:
  traefik:
    external: true
  mysql:
    external: true
  lokal:
    external: true
  mail:
    name: mail

services:
  webmail:
    image: cypht/cypht:2.0.1
    container_name: webmail
    volumes:
    - "{{app_root}}/webmail:/var/lib/hm3/users"
    environment:
      AUTH_USERNAME: "admin"
      AUTH_PASSWORD: "{{password_admin}}"
      DB_CONNECTION_TYPE: host
      DB_DRIVER: mysql
      DB_HOST: {{mysql_host}}
      DB_NAME: cypht
      DB_USER: cypht
      DB_PASS: cypht
      AUTH_TYPE: IMAP
      IMAP_AUTH_SERVER: "mail"
      IMAP_AUTH_PORT: 143
      DEFAULT_SMTP_SERVER: "mail.{{domain}}"
      DEFAULT_SMTP_PORT: 465
      SESSION_TYPE: PHP
      DEFAULT_EMAIL_DOMAIN: "{{domain}}"
      ENABLE_MEMCACHED: false
      ENABLE_REDIS: false
      SINGLE_SERVER_MODE: true
      DEFAULT_LANGUAGE: en
    networks:
    - mysql
    - traefik
    - mail
    labels:
      traefik.enable: "true"
      traefik.http.routers.mail.entrypoints: websecure
      traefik.http.routers.mail.rule: Host(`mail.{{domain}}`)
      traefik.http.routers.mail.tls: "true"
      traefik.http.services.mail.loadbalancer.server.port: 80
{% if ssl_use_acme %}
      traefik.http.routers.mail.tls.certresolver: {{cert_resolver}}
{% endif %}

  mail:
    image: foxcpp/maddy:{{app_version}}
    container_name: mail
    networks:
    - lokal
    - mail
    ports:
    - "465:465"  # ESMTP (implicit TLS)
    - "993:993"  # IMAP4 (implicit TLS)
    # - "25:25"    # SMTP  (explicit TLS => STARTTLS)
    # - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
    # - "587:587"  # ESMTP (explicit TLS => STARTTLS)
    volumes:
    - {{app_root}}/data/:/data
    - {{project_root}}/.certs/mail.{{domain}}:/etc/ssl:ro
    restart: always
    stop_grace_period: 1m
    environment:
      MADDY_HOSTNAME: "mail"
      MADDY_DOMAIN: "{{domain}}"
    depends_on:
    - webmail

  # mail:
  #   image: docker.io/mailserver/docker-mailserver:latest
  #   container_name: mail
  #   hostname: "mail.{{domain}}"
  #   domainname: "mail.{{domain}}"
  #   env_file: "{{app_root}}/mailserver.env"
  #   cap_add:
  #   - NET_ADMIN
  #   ports:
  #   - "465:465"  # ESMTP (implicit TLS)
  #   - "993:993"  # IMAP4 (implicit TLS)
  #   # - "25:25"    # SMTP  (explicit TLS => STARTTLS)
  #   # - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
  #   # - "587:587"  # ESMTP (explicit TLS => STARTTLS)
  #   networks:
  #   - ldap
  #   - mail
  #   volumes:
  #   - {{app_root}}/mail/data/:/var/mail/
  #   - {{app_root}}/mail/state/:/var/mail-state/
  #   - {{app_root}}/mail/logs/:/var/log/mail/
  #   - {{app_root}}/mail/config/:/tmp/docker-mailserver/
  #   - {{project_root}}/lokal/traefik/acme/acme.json:/etc/letsencrypt/acme.json:ro
  #   restart: always
  #   stop_grace_period: 1m
  #   depends_on:
  #   - webmail
  #   healthcheck:
  #     test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
  #     timeout: 3s
  #     retries: 0
