services:
  adminer:
    image: adminer
    restart: no
    environment:
      - ADMINER_DEFAULT_SERVER={{mysql_host}}
    networks:
      - traefik # necessary for extenal access to your app (via a domain name)
      - lokal # necessary if you want to use the external mysql database
    labels:
      traefik.enable: "true"
      traefik.http.routers.adminer.entrypoints: websecure
      traefik.http.routers.adminer.rule: Host(`{{app_domain}}`)
      traefik.http.routers.adminer.tls: "true"
      traefik.http.routers.adminer.middlewares: admin-auth@file
      traefik.http.services.adminer.loadbalancer.server.port: 8080

networks:
  traefik:
    external: true
  lokal:
    external: true