
networks:
  traefik:
    external: true

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:{{app_version}}
    user: "{{uid}}:{{gid}}"
    networks:
    - lokal
    restart: unless-stopped
    volumes:
    - type: bind
      source: "{{app_root}}/config/"
      target: "/etc/prometheus/"
    - type: bind
      source: "{{app_root}}/data/"
      target: "/prometheus/"
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
{% include "labels.yml" %}  # labels expect app_domain to be set and app_port to be set if different than 80
