[backend] 
  datastore = "plugin"
  plugin = "mysql.so"
  pluginhandler = "NewMySQLHandler"
  database = "ldap:ldap@{{mysql_host}}"

  baseDN = "{{ldap_domain}}"
  nameformat = "cn"  # default search attribute 
  groupformat = "ou"

[ldap]
  enabled = true
  # run on a non privileged port
  listen = "0.0.0.0:{{ldap_port}}"
  tls = false # enable StartTLS support

[ldaps]
  enabled = false

[[users]]
  name = "admin"
  uidnumber = 5001
  primarygroup = 5500
  passsha256 = "{{ password_admin | hash('sha256') }}"

[[groups]]
  name = "admin"
  gidnumber = 5500

[[groups]]
  name = "mail"
  gidnumber = 5501

[[groups]]
  name = "editors"
  gidnumber = 5502
