# [backend] 
#   datastore = "plugin"
#   plugin = "mysql.so"
#   pluginhandler = "NewMySQLHandler"
#   database = "ldap:ldap@tcp({{mysql_host}}:{{mysql_port}})/ldap"

#   baseDN = "{{ldap_domain}}"
#   nameformat = "cn"  # default search attribute 
#   groupformat = "ou"

[backend]
  datastore = "config"
  baseDN = "{{ldap_domain}}"
  nameformat = "cn"  # default search attribute 
  groupformat = "ou"

[ldap]
  enabled = true
  # run on a non privileged port
  listen = "0.0.0.0:{{ldap_port}}"
  tls = false # enable StartTLS support

[ldaps]
  enabled = false
