name: Maintain

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  maintain:
    runs-on: ubuntu-latest
    steps:
    - name: Install wireguard
      env:
        NEXTCLOUD_USER: ${{ secrets.NEXTCLOUD_USER }}
        NEXTCLOUD_APIKEY: ${{ secrets.NEXTCLOUD_APIKEY }}
      run: |
        curl -Ls get.lokal.network/wg | sudo -E bash -
    - name: Ping devices
      run: |
        echo -e "${{ secrets.IP_MANIFEST }}" | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' | while read IP
          do ping -c 1 "${IP}" > /dev/null
          if [ $? -eq 0 ]
          then
            echo "${IP} is up"
          else
            echo "${IP} is down"
          fi
        done
