name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          cd /tmp
          wget https://releases.hashicorp.com/packer/1.6.6/packer_1.6.6_linux_amd64.zip -O temp.zip
          unzip temp.zip
          chmod 0600 packer
          HOME_BIN="${HOME}/.local/bin"
          mkdir -p "${HOME_BIN}"
          echo "${HOME_BIN}" >> $GITHUB_PATH
          mv packer "${HOME_BIN}"
          rm temp.zip

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible with roles
        run: |
          pip3 install ansible
          ansible-galaxy install -r "${GITHUB_WORKSPACE}/config/ansible/requirements.yml"

      - name: Build with Packer
        run: |
          cd "${GITHUB_WORKSPACE}/config/packer"
          packer build base.json
        env:
          HCLOUD_TOKEN: ${{secrets.HCLOUD_TOKEN}}
          HCLOUD_IMAGE: ubuntu-20.04
          HCLOUD_LOCATION: fsn1
          CLOUD_SSH_USER: root
          PRIMARY_USER: ubuntu
