name: Maintain

on:
  workflow_dispatch:

jobs:
  maintain:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install wireguard
      run: curl -Ls get.lokal.network/wg | sudo bash
      shell: bash
      env:
        NEXTCLOUD_USER: ${{ secrets.NEXTCLOUD_USER }}
        NEXTCLOUD_APIKEY: ${{ secrets.NEXTCLOUD_APIKEY }}

    - name: Ping devices
      run: |
        echo -e "${IP_MANIFEST}" | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' | while read IP
          do ping -c 1 "${IP}" > /dev/null
          if [ $? -eq 0 ]
          then
            echo "${IP} is up"
          else
            echo "${IP} is down"
          fi
        done
