name: Maintain

on:
  workflow_dispatch:

jobs:
  maintain:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install wireguard
      run: |
        export NEXTCLOUD_USER=${{ secrets.NEXTCLOUD_USER }}
        export NEXTCLOUD_APIKEY=${{ secrets.NEXTCLOUD_APIKEY }}
        export DEBIAN_FRONTEND=noninteractive
        curl -Ls get.lokal.network/wg | sudo bash

    - name: Ping devices
      run: |
        echo -e "${IP_MANIFEST}" | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' | while read IP
          do ping -c 1 "${IP}" > /dev/null
          if [ $? -eq 0 ]
          then
            echo "${IP} is up"
          else
            echo "${IP} is down"
          fi
        done
