name: Maintain

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  maintain:
    runs-on: ubuntu-latest
    steps:
    - name: Install wireguard
      env:
        NEXTCLOUD_USER: ${{ secrets.NEXTCLOUD_USER }}
        NEXTCLOUD_APIKEY: ${{ secrets.NEXTCLOUD_APIKEY }}
      run: |
        curl -Ls get.lokal.network/wg | sudo -E bash -
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Ping devices
      run: |
        set +e
        grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' .github/ip.manifest | while read IP
          do ping -c 1 "${IP}" > /dev/null
          if [ $? -eq 0 ]
          then
            echo "${IP} is up"
            rsync -e "ssh -o StrictHostKeyChecking=no" -arvc ubuntu@10.179.0.24:/media/certs/lokal.network/ ubuntu@${IP}:/media/ssl/certs/lokal.network/
            if [ $? -eq 0 ]
            then
              ssh -o StrictHostKeyChecking=no ubuntu@${IP} 'touch /home/ubuntu/Lokal/config/services/traefik/config/local/dynamic.yml'
            fi
          else
            echo "${IP} is down"
          fi
        done
