---
- name: Install docs
  include_role:
    name: lokal
    tasks_from: install
  vars:
    app: docs
    data_dirs:
    - data
    - web
    start: false

- name: Stop running server
  ansible.builtin.shell: 
    cmd: "docker compose down"
    chdir: "{{app_root}}"

- name: Clear old markdown files
  ansible.builtin.file:
    path: "{{app_root}}/data/docs/"
    state: absent

- name: Clear old build
  ansible.builtin.file:
    path: "{{app_root}}/data/web/"
    state: absent

- name: Update markdown files
  ansible.builtin.copy:
    src: "docs/docs"
    dest: "{{app_root}}/data/"
    force: true # always update

- name: Clear old build
  ansible.builtin.file:
    path: "{{app_root}}/data/web/"
    state: directory

- name: Copy mkdocs config
  ansible.builtin.copy:
    src: "docs/mkdocs.yml"
    dest: "{{app_root}}/data/"
    force: true # always update

- name: Correct domain name
  ansible.builtin.lineinfile:
    path: "{{app_root}}/data/mkdocs.yml"
    line: "site_url: https://{{subdomain_docs}}.{{domain}}/"
    state: present
    search_string: "site_url: https://docs.lokal.network/"

- name: Start the build and server
  ansible.builtin.shell: 
    cmd: "docker compose up -d"
    chdir: "{{app_root}}"