global:
  scrape_interval: 1m
  evaluation_interval: 1m
  # ?what is this?
  # external_labels:
  #   monitor: "vnet-monitor"

rule_files:
  - alert.yml

scrape_configs:
  - job_name: "docker"
    static_configs:
    - targets: ["localhost:9323"]

  - job_name: "traefik"
    static_configs:
    - targets: ["traefik:8082"]

  - job_name: "docker-containers"
    docker_sd_configs:
    - host: unix:///var/run/docker.sock
    relabel_configs:
    # keep only containers bind to prometheus network
    - source_labels: [__meta_docker_container_network_name]
      regex: prometheus
      action: keep
    # scrape only targets that have declared their scraping port
    - source_labels: [__meta_docker_container_label_prometheus_port]
      target_label: __meta_docker_port_private
      action: keepequal
    # set container name as instance name
    - source_labels: [__meta_docker_container_name]
      target_label: instance
    # change the default /metrics path if your app serves the metrics on a different endpoint
    - source_labels: [__meta_docker_container_label_prometheus_path]
      target_label: __metrics_path__
    # default interval is "60s" (or "1m") and you can change it here
    - source_labels: [__meta_docker_container_label_prometheus_interval]
      target_label: __scrape_interval__
    # Use all labels prefixed by `prometheus-` for metrics labels
    - regex: __meta_docker_container_label_prometheus_(.+)
      action: labelmap
      replacement: $1